server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssm_mybatis?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  application:
    name: service_provider  #作为微服务的名称
mybatis:
  type-aliases-package: cn.figo.service.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka