server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssm_mybatis?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
mybatis:
  type-aliases-package: cn.figo.service.pojo
