server:
  port: 10087
spring:
  application:
    name: figo_eureka  #作为微服务的名称
eureka:
  client:
    service-url:
      # defaultZone: http://localhost:${server.port}/eureka
      defaultZone: http://localhost:10086/eureka
  server:
    eviction-interval-timer-in-ms: 5000  #失效剔除时间
